---
- name: "Start Logstash"
  systemd:
    name: logstash
    daemon_reload: yes
    enabled: yes
    state: started

- name: "Restart Logstash"
  systemd:
    name: logstash
    daemon_reload: yes
    state: restarted
